env:
  es6: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  prettier/prettier: error
plugins:
  - prettier
globals: 
  beforeAll: readonly
  afterAll: readonly
  describe: readonly
  expect: readonly
  test: readonly
  it: readonly
