# docker-compose.yml
version: '3.3'
services:
  garo3p-server-rack:
    image: mountaindude/garo-gnm3d-moxa:1.0.0
    container_name: garo3p-server-rack
    restart: always
    volumes:
      - "./config:/nodeapp/config"      # Make config file accessible outside of container
      - "./logs:/nodeapp/logs"
    environment:
      - "NODE_ENV=production"           # Read config data from production.yaml 
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
